/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login.rkfms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import static javax.swing.UIManager.getInt;


/**
 *
 * @author gs671
 */
public class SignUpPage extends javax.swing.JFrame {

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        initComponents();
    }
    int id=0;
int getId()
{
    ResultSet rs=null;
 try{
 Class.forName("com.mysql.cj.jdbc.Driver");
 String url="jdbc:mysql://127.0.0.1:3306/rkfms?zeroDateTimeBehavior=CONVERT_TO_NULL";
 Connection con=DriverManager.getConnection(url,"root","gaurav@123");
 String sql="select max(id) from signup";
 Statement st=con.createStatement();
 rs=st.executeQuery(sql);
 while(rs.next())
 {
     id=rs.getInt(1);
  id++;

 }
}
 catch(Exception e)
 {
 e.printStackTrace();
 
 }
 return id;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cnumber1 = new javax.swing.JTextField();
        fname1 = new javax.swing.JTextField();
        lname1 = new javax.swing.JTextField();
        p2 = new javax.swing.JPasswordField();
        p1 = new javax.swing.JPasswordField();
        uname1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dob1 = new com.toedter.calendar.JDateChooser();
        clear = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        cnerror = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        p1error = new javax.swing.JLabel();
        p2error1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("SignUP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(327, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("D.O.B");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 140, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 90, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 100, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Username");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 100, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 100, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Confirm Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 150, 20));

        cnumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnumber1ActionPerformed(evt);
            }
        });
        cnumber1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnumber1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnumber1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cnumber1KeyTyped(evt);
            }
        });
        getContentPane().add(cnumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 230, -1));
        getContentPane().add(fname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 230, -1));
        getContentPane().add(lname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 230, -1));

        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 230, -1));

        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        p1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                p1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                p1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                p1KeyTyped(evt);
            }
        });
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 230, -1));

        uname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uname1ActionPerformed(evt);
            }
        });
        getContentPane().add(uname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 230, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Contact Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 140, 20));
        getContentPane().add(dob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 320, 230, -1));

        clear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 100, 40));

        signup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        signup.setText("SignUp");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 100, 40));

        cnerror.setBackground(new java.awt.Color(255, 51, 51));
        cnerror.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cnerror.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(cnerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 150, 20));

        login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 100, 40));

        p1error.setBackground(new java.awt.Color(255, 51, 51));
        p1error.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        p1error.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(p1error, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 150, 20));

        p2error1.setBackground(new java.awt.Color(255, 51, 51));
        p2error1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        p2error1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(p2error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 150, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnumber1ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2ActionPerformed

    private void uname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uname1ActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
validation();
if(validation())
{
 insertData();
}
else
{
JOptionPane.showMessageDialog(this,"Validation Issue");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_signupActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed

    private void p1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p1KeyPressed
      passwordCheck();  // TODO add your handling code here:
    }//GEN-LAST:event_p1KeyPressed

    private void p1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p1KeyReleased
       passwordCheck(); // TODO add your handling code here:
    }//GEN-LAST:event_p1KeyReleased

    private void p1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p1KeyTyped
      passwordCheck();  // TODO add your handling code here:
    }//GEN-LAST:event_p1KeyTyped

    private void cnumber1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnumber1KeyPressed
mobileCheck();        // TODO add your handling code here:
    }//GEN-LAST:event_cnumber1KeyPressed

    private void cnumber1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnumber1KeyReleased
mobileCheck();        // TODO add your handling code here:
    }//GEN-LAST:event_cnumber1KeyReleased

    private void cnumber1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnumber1KeyTyped
mobileCheck();        // TODO add your handling code here:
    }//GEN-LAST:event_cnumber1KeyTyped

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
      Login l1=new Login();
      //l1.show();
      l1.setVisible(true);
      this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
    fname1.setText("");
    lname1.setText("");;
    uname1.setText("");
    p1.setText("");
    p2.setText("");
    cnumber1.setText("");
    //dob1.getDate();
    // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed
String fname,lname,uname,password,cpassword,cnumber;
Date dob;
 void insertData()
 {
    SimpleDateFormat s1=new SimpleDateFormat("yyyy-MM-dd");
    String mydob=s1.format(dob);
     try{
 Class.forName("com.mysql.cj.jdbc.Driver");
 String url="jdbc:mysql://127.0.0.1:3306/rkfms?zeroDateTimeBehavior=CONVERT_TO_NULL";
 Connection con=DriverManager.getConnection(url,"root","gaurav@123");
 String sql="insert into signup values(?,?,?,?,?,?,?)";
 PreparedStatement st=con.prepareStatement(sql);
      st.setInt(1,getId());
      st.setString(2,fname);
      st.setString(3,lname);
      st.setString(4,uname);
      st.setString(5,password);
      st.setString(6,cnumber);
      st.setString(7,mydob);
      int i=st.executeUpdate();
      if(i>0)
      {
       JOptionPane.showMessageDialog(this,"Record Inserted Succesfully.");
      }
      else
      {
      JOptionPane.showMessageDialog(this,"Record not Inserted Succesfully.");
      }



      
 }
 catch(Exception e)
         {
              e.printStackTrace();

         }
 }
boolean validation()
    {
    fname=fname1.getText();
    lname=lname1.getText();
    uname=uname1.getText();
    password=p1.getText();
    cpassword=p2.getText();
    cnumber=cnumber1.getText();
    dob=dob1.getDate();
    if(fname.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Please Enter First name....");
        return false;
    }
      if(lname.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Please Enter Last name....");
        return false;
    }
       if(uname.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Please Enter UserName....");
        return false;
    }
        if(password.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Please Enter Passwordd....");
        return false;
    }
         if(cpassword.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Please Enter Confirm Password....");
        return false;
    } if(cnumber.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Please Enter Contact Number....");
        return false;
    }
    if(dob.equals(null))
    {
        JOptionPane.showMessageDialog(this,"Please Enter Date Of Birth....");
        return false;
    }
        return true; 
    }
    void passwordCheck()
    {
        password=p1.getText();
        if(password.length()>=8)
        {
        p1error.setText("");
        }
        else
        {
          p1error.setText("Enter Minimum 8 Digit Password.");
        }
    }
    void mobileCheck()
    {
     cnumber=cnumber1.getText();
     if(cnumber.length()==10)
     {     
         cnerror.setText("");
      }
     else
     {
     cnerror.setText("Enter 10 digit Number");
     }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JLabel cnerror;
    private javax.swing.JTextField cnumber1;
    private com.toedter.calendar.JDateChooser dob1;
    private javax.swing.JTextField fname1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname1;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField p1;
    private javax.swing.JLabel p1error;
    private javax.swing.JPasswordField p2;
    private javax.swing.JLabel p2error1;
    private javax.swing.JButton signup;
    private javax.swing.JTextField uname1;
    // End of variables declaration//GEN-END:variables
}
